@startuml
hide empty members

package ska_oso_pdm.entities {
    package common {
        package sdp {
            package sdp_configuration.py <<Rectangle>> {
            }

            package scan_type.py <<Rectangle>> {
            }

            package processing_block.py <<Rectangle>> {
            }

            note as N20
                Together, these model
                SDHP allocation and
                configuration.
            end note

            note as p1
                There are multiple entities
                for SDHP allocation and
                configuration so it is
                implemented as a package.
            end note

            N20 -- sdp_configuration.py
            N20 -- scan_type.py
            N20 -- processing_block.py
        }
	}
}

package ska_oso_pdm.entities {
    package mid {
	package csp_configuration.py <<Rectangle>> {
		note as N1
			Models CSP
			configuration.
		end note
	}

	package dish_allocation.py <<Rectangle>> {
		note as N2
			Models SKA MID
			dish allocation.
		end note
	}

	package dish_configuration.py <<Rectangle>> {
		note as N3
			Models SKA MID
			dish configuration.
		end note
	}

	package target.py <<Rectangle>> {
		note as N4
			Models receptor
			pointings.
		end note
	}

	package sb_definition.py <<Rectangle>> {
		note as N5
			Models SB
			composition.
		end note
	}

	package scan_definition.py <<Rectangle>> {
		note as N6
			Models scan
			configuration.
		end note
	}

	note as simple
		The entities for these
		concepts are simple
		and are implemented in
		a single Python module.
	end note

    simple -- csp_configuration.py
    simple -- dish_allocation.py
    simple -- dish_configuration.py
    simple -- target.py
    simple -- sb_definition.py
    simple -- scan_definition.py

    target.py -[hidden]-> sdp
    }

}

@enduml
