@startuml
hide empty members

package ska_oso_pdm.entities.mid {
	package csp_configuration <<Rectangle>> {
	    class CSPConfiguration
	    class FSPConfiguration
	}

	package dish_allocation <<Rectangle>> {
	    class DishAllocation
	}

	package dish_configuration <<Rectangle>> {
	    class DishConfiguration
	}

	package target <<Rectangle>> {
	    class Target
	}

	package sb_definition <<Rectangle>> {
	    class SBDefinition
	}

	package scan_definition <<Rectangle>> {
	    class ScanDefinition
	}
}

package ska.cdm.schemas.mid {
	package csp_configuration as P1 <<Rectangle>> {
		class CSPConfigurationSchema
		class FSPConfigurationSchema
	}

	package dish_allocation as P3 <<Rectangle>> {
		class DishAllocationSchema
	}

	package dish_configuration as P4 <<Rectangle>> {
		class DishConfigurationSchema
	}

	package target as P5 <<Rectangle>> {
		class TargetSchema
	}

	package sb_definition as P6 <<Rectangle>> {
		class SBDefinitionSchema
	}

	package scan_definition as P7 <<Rectangle>> {
		class ScanDefinitionSchema
	}
}

SBDefinition --- SBDefinitionSchema
ScanDefinition --- ScanDefinitionSchema
DishAllocation --- DishAllocationSchema
DishConfiguration --- DishConfigurationSchema
Target --- TargetSchema
CSPConfiguration --- CSPConfigurationSchema
FSPConfiguration --- FSPConfigurationSchema

@enduml
