# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        exclude: charts/ska-oso-pht-services*/templates/
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: ^(src/|tests/)
        exclude: src/ska_oso_pht_services/generated
        language_version: python3
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: ^(src/|tests/)
        exclude: src/ska_oso_pht_services/generated
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: src/ska_oso_pht_services/generated
        files: ^(src/|tests/)
