openapi: 3.0.0
info:
  title: Proposal Handling Tool Services API
  description: 'This OpenAPI document defines the API for the Proposal Handling Tool Services (PHT) backend service'
  license:
    name: BSD-3-Clause
    url: https://opensource.org/licenses/BSD-3-Clause
  version: 1.0.0
servers:
# This default is overwritten when the application is deployed to include the actual namespace if it is different to the 'ska-oso-pht-services' default
- url: /ska-oso-pht-services/pht/api/v1/
paths:
  /create-proposal:
    post:
      summary: Create a proposal
      description: |
        Create a proposal
      operationId: ska_oso_pht_services.api.proposal_create
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /proposal/{proposal_id}:
    parameters:
      - name: proposal_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
    get:
      summary: Get a proposal
      description: |
        Get a proposal
      operationId: ska_oso_pht_services.api.proposal_get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
    put:
      summary: Edit a proposal
      description: |
        Edit a proposal
      operationId: ska_oso_pht_services.api.proposal_edit
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /proposal/validate:
    post:
      summary: Validate a proposal
      description: |
        Validate a proposal
      operationId: ska_oso_pht_services.api.proposal_validate
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /proposal/list:
    get:
      summary: Get a list of proposal
      description: |
        Validate a proposal
      operationId: ska_oso_pht_services.api.proposal_get_list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema: {}
  /upload/pdf:
    post:
      summary: Upload a pdf
      description: |
        Upload a pdf
      operationId: ska_oso_pht_services.api.upload_pdf
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
  /coordinates/{identifier}:
    get:
      summary: get coordinates
      description: |
        get coordinates
      operationId: ska_oso_pht_services.api.get_coordinates
      parameters:
      - name: identifier
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string