apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-pht-services.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-pht-services.labels" . | indent 4 }}
    component:  {{ template "ska-oso-pht-services.name" . }}
    domain: environment
    function: ska-oso-pht-services-environment
    intent: production
data:
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  ODA_BACKEND_TYPE: {{ .Values.rest.oda.backendType }}
  {{- if .Values.rest.oda.url }}
  ODA_URI: {{ .Values.rest.oda.url }}
  {{ end }}
  SKUID_URL: ska-ser-skuid-{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.cluster.local:9870
  {{- if not .Values.rest.use_skuid }}
  FAKE_SKUID: "true"
  {{ end }}
