apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ska-oso-pht-services.name" . }}-{{ .Values.rest.component }}-{{ .Release.Name }}-environment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ska-oso-pht-services.labels" . | indent 4 }}
    component:  {{ template "ska-oso-pht-services.name" . }}
    domain: environment
    function: ska-oso-pht-services-environment
    intent: production
data:
  KUBE_NAMESPACE: {{ .Release.Namespace }}
  ODA_BACKEND_TYPE: {{ .Values.rest.oda.backendType }}
  POSTGRES_HOST: {{ if .Values.rest.oda.postgres.host }} {{ .Values.rest.oda.postgres.host }} {{ else }} {{ .Release.Name }}-postgresql {{ end }}
  ADMIN_POSTGRES_PASSWORD: {{ .Values.rest.oda.postgres.password }}
  {{ if .Values.rest.oda.postgres.port }}
  POSTGRES_PORT: {{ .Values.rest.oda.postgres.port | quote }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.db.name }}
  POSTGRES_DB_NAME: {{ .Values.rest.oda.postgres.db.name }}
  {{ end }}
  {{ if .Values.rest.oda.postgres.user }}
  ADMIN_POSTGRES_USER: {{ .Values.rest.oda.postgres.user }}
  {{ end }}
  {{- if .Values.rest.oda.url }}
  ODA_URL: {{ .Values.rest.oda.url }}
  {{- else }}
  ODA_URL: http://ska-db-oda-rest-{{ .Release.Name }}:5000/{{ .Release.Namespace }}/oda/api/v6
  {{- end }}
  SKUID_URL: ska-ser-skuid-{{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc.{{ .Values.global.cluster_domain }}:9870
  OSD_API_URL: "http://ska-ost-osd-rest-{{ .Release.Name }}:5000/{{ .Release.Namespace }}/osd/api/v1"
