---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
name: test
spec:
provider: {{ .Values.secretProvider.provider.name | default "vault" }}
secretObjects:
    - secretName: {{ .Values.secretProvider.name }}
    type: Opaque
    data:
        {{- range .Values.secretProvider.provider.secrets }}
        - objectName: {{ .secretKey }}
        key: {{ .secretKey }}
        {{- end }}
        {{- if .Values.secretProvider.testDeployment }}
        {{- range .Values.secretProvider.provider.testSecrets }}
        - objectName: {{ .secretKey }}
        key: {{ .secretKey }}
        {{- end }}
        {{- end }}
parameters:
    vaultAddress: {{ .Values.secretProvider.provider.vaultAddress }}
    roleName: {{ .Values.secretProvider.provider.roleName }}
    objects: |
    {{- range .Values.secretProvider.provider.secrets }}
    - objectName: {{ .secretKey }}
        secretPath: {{ $.Values.secretProvider.provider.secretsPath }}
        secretKey: {{ .secretKey }}
    {{- end }}
    {{- if .Values.secretProvider.testDeployment }}
    {{- range .Values.secretProvider.provider.testSecrets }}
    - objectName: {{ .secretKey }}
        secretPath: {{ $.Values.secretProvider.provider.secretsPath }}
        secretKey: {{ .secretKey }}
    {{- end }}
    {{- end }}