@startuml
hide empty members

package ska_oso_pdm.entities.dish {
    package dish_configuration <<Rectangle>> {
        class DishConfiguration {
            dish_configuration_id: DishConfigurationID
            receiver_band: ReceiverBand
        }

        class DishConfigurationID

        enum ReceiverBand {
            BAND_1
            BAND_2
            BAND_5A
            BAND_5B
        }
    }
}
@enduml
