@startuml
hide empty members

package ska_oso_pdm.entities.common{
        package sb_definition <<Rectangle>> {
            class SBDefinitionID

            class SBDefinition {
                interface: str
                sbi_id: SBDefinitionID
                metadata: MetaData
                telescope: TelescopeType
                activities: dict[str, PythonProcedure]
                ..
                scan_definitions: List[ScanDefinition]
                scan_sequence: List[ScanDefinitionID]
                .. Common ..
                targets: List[Target]
                sdp_configurations: List[SDPConfiguration]
                csp_configurations: List[CSPConfiguration]
                .. SKA LOW ..
                mccs_allocation: MCCSAllocation
                target_beam_configurations: List[TargetBeamConfiguration]
                subarray_beam_configurations: List[SubarrayBeamConfiguration]
                .. SKA MID ..
                dish_allocation: DishAllocation
                dish_configurations: List[DishConfiguration]
            }

            enum TelescopeType {
            SKA1_MID
            SKA1_LOW
            MeerKAT
            }

            class MetaData{
            version: int
            created_by: str
            created_on: datetime.datetime
            last_modified_on:datetime.datetime
            last_modified_by: str

            }
        }
}
@enduml
