system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-pht-services

global:
  minikube: false
  env:
    aws_pht_bucket_name:
    aws_server_public_key:
    aws_server_secret_key:
    smtp_password:
  cluster_domain: techops.internal.skao.int

rest:
  component: rest
  function: pht-services
  domain: operations
  logLevel: info
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-oso-pht-services
    tag: 2.2.0-dirty # Defaults to the chart appVersion if not set
    pullPolicy: IfNotPresent
  oda:
    backendType: postgres
    postgres: # The below values are used to set environment variables that are used in the ODA Repository. If they are not set then the defaults defined by the ODA will be used.
      host: ~
      port: ~
      user: ~
      password: secretpassword # TODO BTN-2449 will extract this
      db:
        name: ~
  use_skuid: true
  skuid:
    url:
  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  ingress:
    enabled: true

nodeSelector: {}

affinity: {}

tolerations: []

secretProvider:
  enabled: true
  provider:
    name: "vault"
    vaultAddress: "https://vault.skao.int"
    roleName: "kube-role"
    secretsPath: "kv/data/users/jackmktam/pht_s3_bucket"
    secrets:
    - secretKey: "aws_pht_bucket_name"
      targetEnv: AWS_PHT_BUCKET_NAME
    - secretKey: "aws_server_public_key"
      targetEnv: AWS_SERVER_PUBLIC_KEY
    - secretKey: "aws_server_secret_key"
      targetEnv: AWS_SERVER_SECRET_KEY
    - secretKey: "smtp_password"
      targetEnv: SMTP_PASSWORD
