# Default values for oet.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
minikube: true

system: TM-mid
telescope: SKA-mid
subsystem: ska-oso-pht-services

global:
  minikube: true
  cluster_domain: techops.internal.skao.int

rest:
  component: rest
  function: pht-services
  domain: operations
  logLevel: info
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-oso-pht-services
    tag: ~ # Defaults to the chart appVersion if not set
    pullPolicy: IfNotPresent
  oda:
    backendType: filesystem
    url: ~ # Defaults to the ODA Kubernetes service address if not set
  use_skuid: true
  resources:
    requests:
      cpu: 100m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
  ingress:
    enabled: true

nodeSelector: {}

affinity: {}

tolerations: []

secretProvider:
  enabled: true
  provider:
    name: "vault"
    vaultAddress: "https://vault.skao.int"
    roleName: "kube-role"
    secretsPath: "kv/data/users/jackmktam/pht_s3_bucket"
    secrets:
    - secretKey: "aws_pht_bucket_name"
      targetEnv: AWS_PHT_BUCKET_NAME
    - secretKey: "aws_server_public_key"
      targetEnv: AWS_SERVER_PUBLIC_KEY
    - secretKey: "aws_server_secret_key"
      targetEnv: AWS_SERVER_SECRET_KEY
