@startuml
hide empty members

package ska_oso_pdm.entities.mccs {
        package mccs_allocation <<Rectangle>> {
            class SubarrayBeamID

            class MCCSAllocation {
                station_ids: List[List[int]]
                channel_blocks: List[int]
                subarray_beam_ids: List[SubarrayBeamID]
            }
        }
}
@enduml
