SBInstance:
  type: object
  required:
    - interface
    - sbi_id
    - metadata
    - telescope
  properties:
    interface:
      type: string
    sbi_id:
      type: string
    metadata:
      $ref: 'common-openapi-v1.yaml#/Metadata'
    telescope:
      $ref: 'common-openapi-v1.yaml#/Telescope'
    sbd_id:
      type: string
    sbd_version:
      type: integer
    executed_on:
      type: string
      format: date-time
    subarray_id:
      type: integer
    runtime_args:
      nullable: true
      $ref: 'common-openapi-v1.yaml#/PythonArguments'
